import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import ConfigProviderApp from "@/config/ConfigProviderApp";
import { AuthProvider } from "@/contexts/Auth/AuthProvider";
import ThemeProvider from "@/contexts/Theme/ThemeProvider";
import { getDictionary } from "@/lib/get-dictionary";
import { I18nProvider } from "@/contexts/i18n/i18nProvider";
import { cookies } from "next/headers";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: {
    children: JSX.Element;
}) {

    const dictionaryVI = await getDictionary('vi');
    const dictionaryEN = await getDictionary('en');

    const cookieStore = await cookies();
    const access = cookieStore.get('access-token')?.value
    const refresh = cookieStore.get('refresh-token')?.value

    return (
        <html lang="en">
            <head />
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <main>
                    <AntdRegistry>
                        <ThemeProvider>
                            <AuthProvider
                                access={access}
                                refresh={refresh}
                            >
                                <ConfigProviderApp>
                                    <I18nProvider
                                        dictionaryEN={dictionaryEN}
                                        dictionaryVI={dictionaryVI}
                                    >{children}</I18nProvider>
                                </ConfigProviderApp>
                            </AuthProvider>
                        </ThemeProvider>
                    </AntdRegistry>
                </main>
            </body>
        </html>
    );
}
